/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  list-council-card-${idx}
 * Captured:  2026-06-25T04:29:17.001Z
 * Duration:  0ms
 * Derived:   files=[package-lock.json, packages/agent-harness-react/src/install.ts, packages/agent-harness-react/src/semantic.tsx, src/index.ts, src/orchestrator/preprocessor.ts, src/orchestrator/prompts.ts, src/orchestrator/stream-runner.ts, src/orchestrator/subagent-compactor.spec.ts, src/orchestrator/subagent-compactor.ts, src/orchestrator/tool-engine.ts, src/pil/discovery.ts, src/storage/transcript-view.ts, src/ui/app.tsx, src/ui/containers/chat-feed.tsx, src/ui/use-app-logic.tsx, tests/harness/auto/smoke-boot.spec.ts, tests/harness/scope-adherence-tui.spec.ts] semanticIds=[council-card-${idx}]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: list-council-card-${idx}",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("Navigate list around 'council-card-${idx}'", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 10000 });
      driver.press_sequence(["Down", "Down", "Up"]);
      await driver.wait_for({ idle: true, timeoutMs: 3000 });

      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 15000);
  },
);
