/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  list-council-phases
 * Captured:  2026-07-06T05:49:06.848Z
 * Duration:  62ms
 * Derived:   files=[.planning/STATE.md, src/council/__tests__/strip-think.test.ts, src/council/llm.ts, src/council/strip-think.ts, src/types/index.ts, src/ui/app.tsx, src/ui/components/__tests__/council-conclusion-card.test.ts, src/ui/components/__tests__/council-status-list.test.ts, src/ui/components/council-conclusion-card.tsx, src/ui/components/council-leader-bubble.tsx, src/ui/components/council-placeholder-bubble.tsx, src/ui/components/council-status-list.tsx, src/ui/components/council-synthesis-banner.tsx, src/ui/use-app-logic.tsx, tests/harness/auto/list-council-card-${idx}.spec.ts, tests/harness/auto/list-council-phases.spec.ts, tests/harness/auto/list-council-status.spec.ts, tests/harness/auto/smoke-boot.spec.ts] semanticIds=[council-phases]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env.MUONROI_SKIP_NAMED_PIPE === "1")(
  "self-qa auto: list-council-phases",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("Navigate list around 'council-phases'", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 10000 });
      driver.press_sequence(["Down", "Down", "Up"]);
      await driver.wait_for({ idle: true, timeoutMs: 3000 });

      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 15000);
  },
);
