/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  list-council-status
 * Captured:  2026-07-08T11:56:05.656Z
 * Duration:  0ms
 * Derived:   files=[docs/superpowers/plans/2026-07-08-clean-resume-thread-aware.md, docs/superpowers/specs/2026-07-08-council-debate-language-design.md, docs/superpowers/specs/2026-07-08-council-detail-readability-design.md, src/council/__tests__/language-rule.test.ts, src/council/debate.ts, src/council/planner.ts, src/council/prompts.ts, src/council/types.ts, src/orchestrator/__tests__/fallback-title.test.ts, src/orchestrator/__tests__/sub-session-delegation.test.ts, src/orchestrator/orchestrator.ts, src/storage/__tests__/migrations.test.ts, src/storage/__tests__/resume-backfill.test.ts, src/storage/__tests__/resume-list.test.ts, src/storage/__tests__/session-store-link.test.ts, src/storage/migrations.ts, src/storage/sessions.ts, src/types/index.ts, src/ui/app.tsx, src/ui/components/__tests__/council-conclusion-card.test.ts, src/ui/components/__tests__/task-list-panel.test.ts, src/ui/components/council-conclusion-card.tsx, src/ui/components/council-rail-rounds.tsx, src/ui/components/council-round-group.tsx, src/ui/components/council-status-list.tsx, src/ui/components/task-list-panel.tsx, src/ui/containers/modals-layer.tsx, src/ui/hooks/use-session-picker.ts, src/ui/modals/session-picker-modal.tsx, src/ui/slash/__tests__/council-lang.test.ts, src/ui/slash/council.ts, src/ui/use-app-logic.tsx, src/utils/settings.test.ts, src/utils/settings.ts, tests/council/council-e2e.test.ts, tests/council/council-edge-cases.test.ts, tests/harness/session-picker.spec.ts] semanticIds=[council-status]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: list-council-status",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("Navigate list around 'council-status'", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 10000 });
      driver.press_sequence(["Down", "Down", "Up"]);
      await driver.wait_for({ idle: true, timeoutMs: 3000 });

      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 15000);
  },
);
