/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  passive-status
 * Captured:  2026-07-03T05:31:14.088Z
 * Duration:  1ms
 * Derived:   files=[.planning/STATE.md, package.json, packages/agent-harness-core/__tests__/lint.spec.ts, packages/agent-harness-core/__tests__/registry.spec.ts, packages/agent-harness-core/src/lint.ts, packages/agent-harness-core/src/protocol.ts, packages/agent-harness-opentui/src/semantic.tsx, scripts/check-semantic-wrap.ts, scripts/ingest-bb-to-ee.mts, src/models/catalog.json, src/orchestrator/__tests__/council-manager.test.ts, src/orchestrator/__tests__/error-forensics.test.ts, src/orchestrator/council-manager.ts, src/orchestrator/error-utils.ts, src/orchestrator/message-processor.ts, src/orchestrator/orchestrator.ts, src/orchestrator/prompts.ts, src/orchestrator/stream-runner.ts, src/orchestrator/tool-engine.ts, src/product-loop/index.ts, src/providers/strategies/zai.strategy.ts, src/providers/wire-debug.ts, src/state/active-run.ts, src/state/status-bar-store.ts, src/tools/registry.ts, src/ui/components/council-info-card.tsx, src/ui/components/prompt-box.tsx, src/ui/slash/__tests__/cost.test.ts, src/ui/slash/cost.ts, src/ui/slash/debug.ts, src/ui/status-bar/index.test.tsx, src/ui/status-bar/index.tsx, src/ui/status-bar/store.test.ts, src/ui/use-app-logic.tsx] semanticIds=[status]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: passive-status",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("Verify passive surface 'status' renders without error", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 10000 });
      await driver.wait_for({ selector: "id=status", timeoutMs: 5000 });

      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
      // expect: selector 'id=status' present
      expect(driver.queryAll("id=status").length).toBeGreaterThan(0);
    }, 13000);
  },
);
