/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  smoke-boot
 * Captured:  2026-06-23T03:46:58.749Z
 * Duration:  0ms
 * Derived:   files=[src/orchestrator/message-processor.ts, src/pil/__tests__/response-tools.test.ts, src/pil/index.ts, src/pil/response-tools.ts, src/ui/components/structured-response-view.tsx] semanticIds=[(none)]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: smoke-boot",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("CLI boots and reaches idle within budget", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 15000 });

      // expect: idle reached within budget (enforced by test timeout)
      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 20000);
  },
);
