/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  smoke-boot
 * Captured:  2026-06-08T00:03:26.017Z
 * Duration:  504ms
 * Derived:   files=[AGENTS.md, bun.lock, package.json, scripts/postinstall.cjs, src/chat/chat-keychain.ts, src/cli/keys.ts, src/index.ts, src/mcp/mcp-keychain.ts, src/orchestrator/compaction.ts, src/orchestrator/message-processor.ts, src/orchestrator/stream-runner.ts, src/pil/agent-operating-contract.ts, src/pil/discovery-types.ts, src/pil/discovery.ts, src/pil/layer16-clarity.ts, src/pil/layer6-output.ts, src/pil/pipeline.ts, src/providers/auth/grok-oauth.ts, src/providers/keychain.ts, src/ui/app.tsx, src/ui/modals/model-picker-modal.tsx, src/verify/entrypoint.ts, tests/harness/bb-aware-ideal.spec.ts, tests/harness/model-picker.spec.ts] semanticIds=[(none)]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { type HarnessContext, spawnHarness } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: smoke-boot",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
    }, 20_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("CLI boots and reaches idle within budget", async () => {
      const { driver } = ctx;
      await driver.wait_for({ idle: true, timeoutMs: 15000 });

      // expect: idle reached within budget (enforced by test timeout)
      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 20000);
  },
);
