/**
 * AUTO-GENERATED by /self-verify — DO NOT hand-edit.
 *
 * Scenario:  smoke-boot
 * Captured:  2026-09-05T10:36:28.480Z
 * Duration:  1713ms
 * Derived:   files=[src/ui/__tests__/modal-focus-picker-layer.test.tsx, src/ui/agents-modal.tsx, src/ui/app.tsx, src/ui/mcp-modal.tsx, src/ui/modal-focus.ts, src/ui/modals/api-key-modal.tsx, src/ui/modals/connect-modal.tsx, src/ui/modals/ee-connect-card.tsx, src/ui/modals/lsp-setup-card.tsx, src/ui/modals/mcp-needs-key-card.tsx, src/ui/modals/model-picker-modal.tsx, src/ui/modals/sandbox-picker-modal.tsx, src/ui/modals/session-picker-modal.tsx, src/ui/modals/update-modal.tsx, src/ui/modals/wallet-picker-modal.tsx, src/ui/plan.tsx, src/ui/schedule-modal.tsx, src/ui/use-app-logic.tsx, tests/harness/ee-connect-card.spec.ts, tests/harness/lsp-setup-card.spec.ts, tests/harness/mcp-needs-key.spec.ts, tests/harness/modal-focus-sweep.spec.ts] semanticIds=[(none)]
 *
 * To rebuild: `muonroi-cli self-verify --since HEAD~1`.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { spawnHarness, type HarnessContext } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: smoke-boot",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("CLI boots and reaches idle within budget", async () => {
      const { driver } = ctx;
      await driver.wait_for({"idle":true,"timeoutMs":15000});
      
      // expect: idle reached within budget (enforced by test timeout)
      // expect: no error toast
      expect(driver.last_event("toast")?.level).not.toBe("error");
    }, 20000);
  },
);
