/**
 * spec-emitter.ts — Part of M5 of Self-QA.
 *
 * Converts a passing Scenario + JudgeResult into a standalone vitest
 * `.spec.ts` file that future CI runs can replay deterministically.
 *
 * Output convention:
 *   tests/harness/auto/{scenarioId}.spec.ts
 *
 * Each emitted spec uses the same `spawnHarness()` helper as hand-written
 * specs, so they integrate with the existing `bun run test:harness` pipeline
 * with zero extra wiring.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Expectation, JudgeResult, Scenario, ScenarioStep } from "./types.js";

export type EmitOptions = {
  /** Directory to write specs into. Default: tests/harness/auto. */
  outDir?: string;
  /** Header banner timestamp; pass to make output deterministic in tests. */
  now?: () => Date;
};

/**
 * Emit a .spec.ts file for a passing scenario.
 * Returns the absolute path of the written file.
 */
export function emitSpec(scenario: Scenario, result: JudgeResult, opts: EmitOptions = {}): string {
  if (result.verdict !== "pass") {
    throw new Error(`emitSpec called on non-passing scenario '${scenario.id}' (verdict=${result.verdict})`);
  }
  const outDir = opts.outDir ?? resolve("tests/harness/auto");
  const now = (opts.now ?? (() => new Date()))();
  const file = resolve(outDir, `${scenario.id}.spec.ts`);

  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, buildSpecSource(scenario, result, now), "utf8");
  return file;
}

function buildSpecSource(scenario: Scenario, result: JudgeResult, now: Date): string {
  const header = banner(scenario, result, now);
  const body = buildTestBody(scenario);
  return `${header}\n${body}`;
}

function banner(scenario: Scenario, result: JudgeResult, now: Date): string {
  const files = scenario.derivedFrom.files.join(", ") || "(none)";
  const ids = scenario.derivedFrom.semanticIds.join(", ") || "(none)";
  return [
    "/**",
    ` * AUTO-GENERATED by /self-verify — DO NOT hand-edit.`,
    ` *`,
    ` * Scenario:  ${scenario.id}`,
    ` * Captured:  ${now.toISOString()}`,
    ` * Duration:  ${result.durationMs}ms`,
    ` * Derived:   files=[${files}] semanticIds=[${ids}]`,
    ` *`,
    ` * To rebuild: \`muonroi-cli self-verify --since HEAD~1\`.`,
    ` */`,
  ].join("\n");
}

function buildTestBody(scenario: Scenario): string {
  const stepLines = scenario.steps.map(stepToCode).filter((l) => l.length > 0);
  const expectLines = scenario.expectations.flatMap(expectationToCode);
  const body = [...stepLines, "", ...expectLines].join("\n      ");
  const safeDesc = escapeForString(scenario.description);

  return `import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { spawnHarness, type HarnessContext } from "../helpers.js";

describe.skipIf(process.platform === "win32" && process.env["MUONROI_SKIP_NAMED_PIPE"] === "1")(
  "self-qa auto: ${escapeForString(scenario.id)}",
  () => {
    let ctx: HarnessContext;

    beforeAll(async () => {
      ctx = await spawnHarness();
      await ctx.driver.wait_for({ idle: true, timeoutMs: 15_000 });
      // 120s: cold agent-mode TUI boot under CPU contention can take 25-46s+
      // (the named-pipe handshake budget alone is 90s). A tighter hook timeout
      // is the wrong constraint and surfaces as a flaky "Hook timed out".
    }, 120_000);

    afterAll(() => {
      ctx?.cleanup();
    });

    it("${safeDesc}", async () => {
      const { driver } = ctx;
      ${body}
    }, ${scenario.budgetMs + 5_000});
  },
);
`;
}

function stepToCode(step: ScenarioStep): string {
  switch (step.op) {
    case "type":
      return `driver.type(${JSON.stringify(step.text)});`;
    case "press":
      return `driver.press(${JSON.stringify(step.key)});`;
    case "press_sequence":
      return `driver.press_sequence(${JSON.stringify(step.keys)});`;
    case "focus":
      return `try { driver.focus(${JSON.stringify(step.selector)}); } catch { /* ambiguous */ }`;
    case "wait_for": {
      const obj: Record<string, unknown> = {};
      if (step.idle) obj["idle"] = true;
      if (step.selector) obj["selector"] = step.selector;
      if (step.event) obj["event"] = step.event;
      obj["timeoutMs"] = step.timeoutMs ?? 5_000;
      return `await driver.wait_for(${JSON.stringify(obj)});`;
    }
  }
}

function expectationToCode(exp: Expectation): string[] {
  switch (exp.kind) {
    case "noErrorToast":
      return [`// expect: no error toast`, `expect(driver.last_event("toast")?.level).not.toBe("error");`];
    case "eventFired":
      return [
        `// expect: event '${exp.event}' fired`,
        `expect(driver.last_event(${JSON.stringify(exp.event)})).not.toBeNull();`,
      ];
    case "eventAbsent":
      return [
        `// expect: event '${exp.event}' absent`,
        `expect(driver.last_event(${JSON.stringify(exp.event)})).toBeNull();`,
      ];
    case "selectorPresent":
      return [
        `// expect: selector '${exp.selector}' present`,
        `expect(driver.queryAll(${JSON.stringify(exp.selector)}).length).toBeGreaterThan(0);`,
      ];
    case "selectorAbsent":
      return [
        `// expect: selector '${exp.selector}' absent`,
        `expect(driver.queryAll(${JSON.stringify(exp.selector)}).length).toBe(0);`,
      ];
    case "idleReached":
      // Already enforced by the trailing wait_for inside scenario steps;
      // no extra runtime assertion needed — vitest test timeout covers it.
      return [`// expect: idle reached within budget (enforced by test timeout)`];
  }
}

function escapeForString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
