import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { emitSpec } from "../spec-emitter.js";
import type { JudgeResult, Scenario } from "../types.js";

const scenario: Scenario = {
  id: "demo-scn",
  description: "demo scenario",
  derivedFrom: { files: ["src/ui/x.tsx"], semanticIds: ["composer"] },
  steps: [
    { op: "wait_for", idle: true, timeoutMs: 5_000 },
    { op: "focus", selector: "id=composer" },
    { op: "type", text: "hello" },
    { op: "press", key: "Enter" },
  ],
  expectations: [
    { kind: "noErrorToast" },
    { kind: "selectorPresent", selector: "id=composer" },
    { kind: "idleReached", withinMs: 5_000 },
  ],
  budgetMs: 10_000,
};

const passResult: JudgeResult = {
  verdict: "pass",
  scenarioId: scenario.id,
  durationMs: 1234,
  checks: [],
};

describe("spec-emitter", () => {
  it("writes a runnable spec for a passing scenario", () => {
    const dir = mkdtempSync(join(tmpdir(), "self-qa-emit-"));
    const file = emitSpec(scenario, passResult, {
      outDir: dir,
      now: () => new Date("2026-05-21T00:00:00Z"),
    });
    expect(file).toContain("demo-scn.spec.ts");
    const src = readFileSync(file, "utf8");
    expect(src).toContain("AUTO-GENERATED by /self-verify");
    expect(src).toContain("describe.skipIf");
    expect(src).toContain("spawnHarness");
    expect(src).toContain('driver.type("hello")');
    expect(src).toContain('driver.press("Enter")');
    expect(src).toContain('driver.queryAll("id=composer")');
    expect(src).toContain('expect(driver.last_event("toast")?.level).not.toBe("error");');
  });

  it("throws on non-passing verdict", () => {
    const dir = mkdtempSync(join(tmpdir(), "self-qa-emit-"));
    expect(() => emitSpec(scenario, { ...passResult, verdict: "fail" }, { outDir: dir })).toThrow(/non-passing/);
  });

  it("emits banner referencing derived files", () => {
    const dir = mkdtempSync(join(tmpdir(), "self-qa-emit-"));
    const file = emitSpec(scenario, passResult, {
      outDir: dir,
      now: () => new Date("2026-05-21T00:00:00Z"),
    });
    const src = readFileSync(file, "utf8");
    expect(src).toContain("src/ui/x.tsx");
    expect(src).toContain("composer");
    expect(src).toContain("2026-05-21T00:00:00.000Z");
  });
});
