#!/usr/bin/env node
/**
 * sync-version.cjs — copies the version + description from package.json into
 * src/generated/version.ts so the CLI can read it without runtime file I/O.
 *
 * Why: `readFileSync(new URL("../package.json", import.meta.url))` works in
 * Node and Bun runtime modes, but `bun build --compile` packs files into a
 * virtual filesystem and the URL no longer resolves. Inlining the constant
 * at build time avoids all three failure modes.
 *
 * Invoked from package.json scripts.build before tsc.
 */
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
const outDir = path.join(ROOT, "src", "generated");
const outFile = path.join(outDir, "version.ts");

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const body = `// AUTO-GENERATED by scripts/sync-version.cjs. DO NOT EDIT BY HAND.
// Sourced from package.json at build time so it survives bun --compile bundling.
export const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};
export const PACKAGE_DESCRIPTION = ${JSON.stringify(pkg.description ?? "")};
`;

fs.writeFileSync(outFile, body, "utf8");
console.log(`  [sync-version] wrote ${path.relative(ROOT, outFile)} (v${pkg.version})`);
