import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { planningArtifact } from "./paths.js";

export interface TaskShipOpts {
  cwd: string;
  notes?: string[];
  commitMessage?: string;
  verifyEvidence?: string;
  changedFiles?: string[];
}

export interface TaskShipResult {
  ok: boolean;
  shipMdPath: string;
  notes: string[];
}

export function readPlanContext(cwd: string): { title: string; planPath: string | null } {
  const planPath = planningArtifact(cwd, "PLAN.md");
  if (!existsSync(planPath)) {
    return { title: "Task delivery", planPath: null };
  }
  const body = readFileSync(planPath, "utf8");
  const h1 = body.match(/^#\s+(.+)$/m);
  return { title: h1?.[1]?.trim() ?? "Task delivery", planPath };
}

export function writeTaskShipMd(
  cwd: string,
  payload: {
    title: string;
    verifyEvidence?: string;
    changedFiles?: string[];
    notes: string[];
    commitMessage?: string;
  },
): string {
  const shipPath = planningArtifact(cwd, "SHIP.md");
  const lines = [
    `# Ship: ${payload.title}`,
    "",
    "## Status",
    "",
    "Ready for delivery (gsd_ship — muonroi-cli native host).",
    "",
  ];
  if (payload.verifyEvidence?.trim()) {
    lines.push("## Verify evidence", "", payload.verifyEvidence.trim(), "");
  }
  if (payload.commitMessage?.trim()) {
    lines.push("## Suggested commit message (unverified — agent-supplied)", "", payload.commitMessage.trim(), "");
  }
  if (payload.changedFiles?.length) {
    lines.push("## Files touched", "");
    for (const f of payload.changedFiles) lines.push(`- ${f}`);
    lines.push("");
  }
  if (payload.notes.length) {
    lines.push("## Notes", "");
    for (const n of payload.notes) lines.push(`- ${n}`);
    lines.push("");
  }
  lines.push("---", `_Generated by gsd_ship at ${new Date().toISOString()}_`, "");
  writeFileSync(shipPath, lines.join("\n"), "utf8");
  return shipPath;
}

/** Task-level ship — SHIP.md only (no git, no README/package.json). */
export function runTaskShip(opts: TaskShipOpts): TaskShipResult {
  const ctx = readPlanContext(opts.cwd);
  let verifyEvidence = opts.verifyEvidence;
  if (!verifyEvidence) {
    const verifyPath = planningArtifact(opts.cwd, "VERIFY.md");
    if (existsSync(verifyPath)) {
      verifyEvidence = readFileSync(verifyPath, "utf8").trim();
    }
  }
  const notes = [...(opts.notes ?? [])];
  const shipMdPath = writeTaskShipMd(opts.cwd, {
    title: ctx.title,
    verifyEvidence,
    changedFiles: opts.changedFiles,
    notes,
    commitMessage: opts.commitMessage,
  });
  notes.push(`Wrote ${shipMdPath}`);
  return { ok: true, shipMdPath, notes };
}
