// src/product-loop/__tests__/language-registry.test.ts
/**
 * F4a — the repo scanners must actually see the repository.
 *
 * Regression origin: `repo-audit.ts` carried its own CODE_EXTENSIONS set with
 * no `.cs`, while `discovery-detection.ts` carried its own SRC_EXT_TO_LANG map
 * that DID have `.cs`. Pointed at D:\sources\CompanyLibs\tcis-libraries (506
 * `.cs` files under src/src, 181 under src/tests) `auditRepo` counted ~0 and
 * emitted "Source files: 1, test files: 0" into the council/sprint-planner
 * context, so the model invented a layout: run mu229bfiaeec wrote 9 `.cs`
 * files into `src/analyzers/`, never referenced by the solution, ~50 minutes
 * wasted.
 *
 * The fixtures below mirror that repo's real shape (verified on disk):
 * manifests at `src/` rather than the repo root, sources at `src/src/<Proj>/`,
 * tests at `src/tests/<Proj>.Tests/`.
 */
import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { detectExistingProject } from "../discovery-detection.js";
import { CODE_EXTENSIONS, isTestDirName, isTestFile, SOURCE_LANGUAGES, SRC_EXT_TO_LANG } from "../language-registry.js";
import { auditAsContextBlock, auditRepo } from "../repo-audit.js";

let cwd = "";

async function makeFixture(layout: Record<string, string>): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "langreg-"));
  for (const [rel, content] of Object.entries(layout)) {
    const full = path.join(root, rel);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, content, "utf-8");
  }
  return root;
}

afterEach(async () => {
  if (cwd) await fs.rm(cwd, { recursive: true, force: true, maxRetries: 10, retryDelay: 50 });
  cwd = "";
});

describe("F4a: auditRepo sees a C# repository", () => {
  it("counts .cs sources under a nested src/src/ and *Tests.cs under src/tests/", async () => {
    const layout: Record<string, string> = {
      "src/TCISLibraries.sln": "Microsoft Visual Studio Solution File\n",
      "src/Directory.Build.props": "<Project><PropertyGroup /></Project>",
    };
    // N = 4 production sources, nested two levels below the top-level src/.
    for (let i = 0; i < 4; i++) {
      layout[`src/src/TCIS.Caching/Cache${i}.cs`] = `namespace TCIS; public class Cache${i} {}`;
    }
    // M = 3 tests, under src/tests/<Proj>.Tests/ — the .NET convention.
    for (let i = 0; i < 3; i++) {
      layout[`src/tests/TCIS.Caching.Tests/Cache${i}Tests.cs`] = `namespace TCIS.Tests; public class T${i} {}`;
    }
    cwd = await makeFixture(layout);

    const a = await auditRepo(cwd);
    expect(a.srcFileCount).toBe(4);
    expect(a.testFileCount).toBe(3);
    expect(a.hasProject).toBe(true);
  });

  it("puts the real counts into the block the council reads (was 'Source files: 1, test files: 0')", async () => {
    const layout: Record<string, string> = { "README.md": "# TCIS\n\nShared libraries.\n" };
    for (let i = 0; i < 6; i++) layout[`src/src/Proj/File${i}.cs`] = "public class A {}";
    for (let i = 0; i < 2; i++) layout[`src/tests/Proj.Tests/File${i}Tests.cs`] = "public class T {}";
    cwd = await makeFixture(layout);

    const block = auditAsContextBlock(await auditRepo(cwd));
    expect(block).toContain("Source files: 6, test files: 2");
  });

  it("does not count generated sources under obj/ as repository source", async () => {
    // tcis-libraries has 630 generated .cs under obj/ vs 506 real ones — counting
    // them would replace one distortion (repo looks empty) with another.
    const layout: Record<string, string> = {};
    for (let i = 0; i < 3; i++) layout[`src/src/Proj/Real${i}.cs`] = "public class A {}";
    for (let i = 0; i < 5; i++) {
      layout[`src/src/Proj/obj/Debug/net8.0/Proj.AssemblyInfo${i}.cs`] = "// <auto-generated/>";
    }
    cwd = await makeFixture(layout);

    expect((await auditRepo(cwd)).srcFileCount).toBe(3);
  });

  it("treats everything under a test directory as a test whatever it is named", async () => {
    const layout: Record<string, string> = {};
    for (let i = 0; i < 2; i++) layout[`src/src/Proj/Prod${i}.cs`] = "public class A {}";
    // Helpers/fixtures inside a test project carry no *Tests.cs suffix.
    layout["src/tests/Proj.Tests/TestFixtureBuilder.cs"] = "public class B {}";
    layout["src/tests/Proj.Tests/Helpers/JsonHelper.cs"] = "public class C {}";
    cwd = await makeFixture(layout);

    const a = await auditRepo(cwd);
    expect(a.srcFileCount).toBe(2);
    expect(a.testFileCount).toBe(2);
  });
});

describe("F4a: a .NET repo is detected as having a manifest", () => {
  it("detects a root-level *.csproj", async () => {
    const layout: Record<string, string> = {
      "Proj.csproj":
        '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>',
    };
    for (let i = 0; i < 10; i++) layout[`src/File${i}.cs`] = "public class A {}";
    cwd = await makeFixture(layout);

    const sig = await detectExistingProject(cwd);
    expect(sig.manifests.length).toBeGreaterThanOrEqual(1);
    expect(sig.manifests[0].type).toBe("csproj");
    expect(sig.languages).toContain("C#");
    expect(sig.classification).toBe("existing");
  });

  it("detects a .sln that lives one level down (the tcis-libraries shape)", async () => {
    // Verified on disk: tcis-libraries has NO manifest at the repo root; its
    // .sln + Directory.Build.props sit under src/.
    const layout: Record<string, string> = {
      "src/TCISLibraries.sln": 'Project("{FAE04EC0}") = "TCIS", "src\\TCIS\\TCIS.csproj"\nEndProject\n',
      "src/Directory.Build.props":
        "<Project><PropertyGroup><LangVersion>latest</LangVersion></PropertyGroup></Project>",
    };
    for (let i = 0; i < 10; i++) layout[`src/src/TCIS/File${i}.cs`] = "public class A {}";
    cwd = await makeFixture(layout);

    const sig = await detectExistingProject(cwd);
    expect(sig.manifests.length).toBeGreaterThanOrEqual(1);
    expect(sig.languages).toContain("C#");
    expect(sig.srcFileCount).toBeGreaterThan(5);
  });

  it("reports one .NET stack, not a polyglot, when sln+props+csproj all appear", async () => {
    // classify() calls >1 manifest "ambiguous". A .NET repo proves itself with
    // several files that are all the SAME stack; they must dedupe to one.
    const layout: Record<string, string> = {
      "App.sln": "Microsoft Visual Studio Solution File\na = b\nc = d\ne = f\ng = h\ni = j\n",
      "App.csproj": '<Project><ItemGroup><PackageReference Include="A" Version="1" /></ItemGroup></Project>',
      "Directory.Build.props": "<Project><PropertyGroup><X>1</X></PropertyGroup></Project>",
    };
    for (let i = 0; i < 10; i++) layout[`src/File${i}.cs`] = "public class A {}";
    cwd = await makeFixture(layout);

    const sig = await detectExistingProject(cwd);
    expect(sig.manifests.length).toBe(1);
    expect(sig.classification).toBe("existing");
  });

  it("still calls a genuinely polyglot repo ambiguous", async () => {
    const layout: Record<string, string> = {
      "App.csproj": '<Project><ItemGroup><PackageReference Include="A" Version="1" /></ItemGroup></Project>',
      "pyproject.toml": "[tool.poetry]\nname='x'\na = 1\nb = 2\nc = 3\nd = 4\ne = 5\n",
    };
    for (let i = 0; i < 10; i++) layout[`src/File${i}.cs`] = "public class A {}";
    cwd = await makeFixture(layout);

    const sig = await detectExistingProject(cwd);
    expect(sig.manifests.length).toBeGreaterThanOrEqual(2);
    expect(sig.classification).toBe("ambiguous");
  });

  it("a root manifest wins — the one-level-down scan never runs for it", async () => {
    // Containment: repos that already have a root manifest must behave exactly
    // as before, so a nested manifest cannot turn them polyglot.
    const layout: Record<string, string> = {
      "package.json": JSON.stringify({ dependencies: { react: "^18", a: "1", b: "1", c: "1", d: "1", e: "1" } }),
      "backend/pyproject.toml": "[tool.poetry]\nname='y'\na = 1\nb = 2\nc = 3\nd = 4\ne = 5\n",
    };
    for (let i = 0; i < 10; i++) layout[`src/f${i}.ts`] = "export {}";
    cwd = await makeFixture(layout);

    const sig = await detectExistingProject(cwd);
    expect(sig.manifests.length).toBe(1);
    expect(sig.manifests[0].type).toBe("package.json");
    expect(sig.classification).toBe("existing");
  });
});

describe("F4a: the two extension lists cannot diverge again", () => {
  it("both derived lookups cover exactly the registry's extensions", () => {
    const registered = SOURCE_LANGUAGES.flatMap((l) => [...l.extensions]).sort();
    expect([...CODE_EXTENSIONS].sort()).toEqual(registered);
    expect(Object.keys(SRC_EXT_TO_LANG).sort()).toEqual(registered);
  });

  it("no extension is claimed by two languages", () => {
    const seen = new Map<string, string>();
    for (const spec of SOURCE_LANGUAGES) {
      for (const ext of spec.extensions) {
        expect(seen.has(ext), `${ext} claimed by ${seen.get(ext)} and ${spec.lang}`).toBe(false);
        seen.set(ext, spec.lang);
      }
    }
  });

  /**
   * The load-bearing pin. Structural equality of two constants could still be
   * satisfied by two hand-lists that happen to agree today. This drives BOTH
   * consumers over a fixture holding one file per registered extension and
   * asserts each one sees all of them — so a language added to the registry
   * cannot leave either scanner blind, which is the exact defect F4a fixes.
   */
  it("every registered language is visible to auditRepo AND detectExistingProject", async () => {
    const exts = SOURCE_LANGUAGES.flatMap((l) => [...l.extensions]);
    const layout: Record<string, string> = {
      // 6+ deps so classify() can reach "existing" rather than scaffold-ambiguous.
      "package.json": JSON.stringify({ dependencies: { a: "1", b: "1", c: "1", d: "1", e: "1", f: "1" } }),
    };
    // Deliberately neutral basenames: none may trip a test-file convention.
    exts.forEach((ext, i) => {
      layout[`src/module${i}${ext}`] = "// sample";
    });
    cwd = await makeFixture(layout);

    const audit = await auditRepo(cwd);
    expect(audit.srcFileCount, "auditRepo must count every registered extension").toBe(exts.length);
    expect(audit.testFileCount).toBe(0);

    const sig = await detectExistingProject(cwd);
    expect(sig.srcFileCount, "detectExistingProject must count every registered extension").toBe(exts.length);
    for (const spec of SOURCE_LANGUAGES) {
      expect(sig.languages, `language "${spec.lang}" missing from detection`).toContain(spec.lang);
    }
  });
});

describe("F4a: test-file and test-dir conventions", () => {
  it.each([
    ["FooTests.cs", true],
    ["FooTest.cs", true],
    ["Foo.cs", false],
    // A case-insensitive `tests?\.cs$` swallows all of these — they are
    // production files whose names merely end in the letters "test".
    ["Latest.cs", false],
    ["Greatest.cs", false],
    ["Protest.cs", false],
    ["Latest.java", false],
    ["Protest.swift", false],
    ["ManifestTests.cs", true],
    ["foo_test.go", true],
    ["foo.go", false],
    ["test_foo.py", true],
    ["foo_test.py", true],
    ["foo.py", false],
    ["FooSpec.scala", true],
    ["foo.test.ts", true],
    ["foo.spec.tsx", true],
    ["foo.ts", false],
    ["foo_test.exs", true],
    ["foo_test.dart", true],
    ["foo_spec.rb", true],
  ])("isTestFile(%s) === %s", (name, expected) => {
    expect(isTestFile(name as string)).toBe(expected);
  });

  it.each([
    ["tests", true],
    ["test", true],
    ["__tests__", true],
    ["spec", true],
    ["TCIS.Caching.Tests", true],
    ["integration-test", true],
    ["src", false],
    ["latest", false],
    ["protest", false],
    ["contest", false],
  ])("isTestDirName(%s) === %s", (name, expected) => {
    expect(isTestDirName(name as string)).toBe(expected);
  });
});

describe("F4a: existing JavaScript/TypeScript behaviour is unchanged", () => {
  it("counts a TypeScript repo exactly as before", async () => {
    cwd = await makeFixture({
      "README.md": "# My Project\n\nA cool tool.\n",
      "package.json": JSON.stringify({ name: "t", devDependencies: { vitest: "1.0.0" } }),
      "src/index.ts": "export const a = 1;",
      "src/foo.ts": "export const b = 2;",
      "src/bar.tsx": "export const c = 3;",
      "src/baz.spec.ts": "test('x', () => {});",
      "tests/foo.test.ts": "test('x', () => {});",
      "vitest.config.ts": "export default {};",
    });

    const a = await auditRepo(cwd);
    expect(a.srcFileCount).toBe(3); // index/foo/bar — baz.spec.ts is a test
    expect(a.testFileCount).toBe(2); // src/baz.spec.ts + tests/foo.test.ts
    expect(a.mode).toBe("upgrade-existing");
    expect(a.testFramework).toBe("vitest");
  });

  it("still ignores node_modules and dist", async () => {
    const layout: Record<string, string> = {
      "package.json": JSON.stringify({ dependencies: { a: "1", b: "1", c: "1", d: "1", e: "1", f: "1" } }),
      "node_modules/lib/f.ts": "export {}",
      "dist/out.js": "export {}",
    };
    for (let i = 0; i < 6; i++) layout[`src/f${i}.ts`] = "export {}";
    cwd = await makeFixture(layout);

    expect((await detectExistingProject(cwd)).srcFileCount).toBe(6);
    expect((await auditRepo(cwd)).srcFileCount).toBe(6);
  });
});
