/**
 * repo-map.ts — Reads or generates REPO_DEEP_MAP.md for a given cwd.
 *
 * Decision D4 (locked): if REPO_DEEP_MAP.md already exists, read it and
 * return immediately. Only generate + write when the file is absent so
 * subsequent runs (and the user) can edit it freely.
 *
 * No LLM calls — pure filesystem heuristics.
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";

export interface RepoMapResult {
  content: string; // truncated to ~2000 chars
  source: "existing" | "generated";
  path: string; // absolute path to the file
}

/** Directories to skip during tree-walk. */
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "out",
  "coverage",
  ".next",
  ".nuxt",
  "target",
  "bin",
  "obj",
  "__pycache__",
  ".venv",
  ".idea",
  ".vscode",
  ".planning",
]);

const MAP_FILE = "REPO_DEEP_MAP.md";
const MAX_CONTENT_CHARS = 2000;
const MAX_GENERATE_CHARS = 1800; // leave 200 for truncation marker + header
const MAX_DEPTH = 4;

/**
 * Read REPO_DEEP_MAP.md if it exists; generate + write a fresh one if not.
 * Implements Decision D4 from MAINTAIN-MODE.md.
 */
export async function ensureRepoMap(cwd: string): Promise<RepoMapResult> {
  const mapPath = path.join(cwd, MAP_FILE);

  // D4: always prefer existing file
  try {
    const raw = await fs.readFile(mapPath, "utf8");
    const content = raw.length <= MAX_CONTENT_CHARS ? raw : `${raw.slice(0, MAX_CONTENT_CHARS)}\n[... truncated]`;
    return { content, source: "existing", path: mapPath };
  } catch {
    // file missing — fall through to generate
  }

  const generated = await generateRepoMap(cwd);

  const header =
    `# REPO_DEEP_MAP\n` + `> Generated by /ideal Mode C. Edit freely; agent will reuse this on subsequent runs.\n\n`;
  const full = header + generated;

  // Atomic write: write to .tmp, then rename
  const tmpPath = `${mapPath}.tmp`;
  try {
    await fs.writeFile(tmpPath, full, "utf8");
    await fs.rename(tmpPath, mapPath);
  } catch {
    // Non-fatal — caller still gets the content even if write failed
    try {
      await fs.unlink(tmpPath).catch(() => undefined);
    } catch {
      // ignore
    }
  }

  const content = full.length <= MAX_CONTENT_CHARS ? full : `${full.slice(0, MAX_CONTENT_CHARS)}\n[... truncated]`;
  return { content, source: "generated", path: mapPath };
}

/**
 * Pure tree-walk generator. Exposed for testing.
 * Walks cwd up to MAX_DEPTH levels, skips SKIP_DIRS + hidden dirs,
 * extracts top-of-file JSDoc/comment for TS/JS/Python/C# files.
 */
export async function generateRepoMap(cwd: string): Promise<string> {
  const lines: string[] = [];
  let totalChars = 0;
  let truncated = false;

  async function walk(dir: string, depth: number, prefix: string): Promise<void> {
    if (truncated) return;
    if (depth > MAX_DEPTH) return;

    let entries: import("node:fs").Dirent[];
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }

    // Sort: directories first, then files, alphabetical within each group
    entries.sort((a, b) => {
      const aDir = a.isDirectory() ? 0 : 1;
      const bDir = b.isDirectory() ? 0 : 1;
      if (aDir !== bDir) return aDir - bDir;
      return a.name.localeCompare(b.name);
    });

    for (const entry of entries) {
      if (truncated) break;
      const name = entry.name;

      // Skip hidden files/dirs and known skip-list dirs
      if (name.startsWith(".")) continue;
      if (entry.isDirectory() && SKIP_DIRS.has(name)) continue;

      const fullPath = path.join(dir, name);
      const relativeToRoot = path.relative(cwd, fullPath);

      if (entry.isDirectory()) {
        const line = `${prefix}${name}/\n`;
        if (totalChars + line.length > MAX_GENERATE_CHARS) {
          lines.push(`${prefix}[… truncated]\n`);
          truncated = true;
          break;
        }
        lines.push(line);
        totalChars += line.length;
        await walk(fullPath, depth + 1, `${prefix}│   `);
      } else {
        const desc = await extractFileDescription(fullPath);
        const descSuffix = desc ? ` (${desc})` : "";
        const line = `${prefix}${name}${descSuffix}\n`;
        if (totalChars + line.length > MAX_GENERATE_CHARS) {
          lines.push(`${prefix}[… truncated]\n`);
          truncated = true;
          break;
        }
        lines.push(line);
        totalChars += line.length;
      }

      void relativeToRoot; // used for debug only
    }
  }

  await walk(cwd, 0, "");
  return lines.join("");
}

/**
 * Extract a 1-line description from the top 10 lines of a source file.
 * Looks for:
 *  - JSDoc block comment: /** ... *\/
 *  - Single-line // comment
 *  - Python/Ruby # comment
 * Returns the first non-trivial comment content, or null.
 */
async function extractFileDescription(filePath: string): Promise<string | null> {
  const ext = path.extname(filePath).toLowerCase();
  const descExts = new Set([".ts", ".tsx", ".js", ".jsx", ".py", ".cs", ".go", ".rs", ".java", ".kt", ".rb"]);
  if (!descExts.has(ext)) return null;

  let content: string;
  try {
    const buf = await fs.readFile(filePath, "utf8");
    // Only look at the first 1 KB — enough for top-of-file comments
    content = buf.slice(0, 1024);
  } catch {
    return null;
  }

  const lines = content.split("\n").slice(0, 10);

  // Try JSDoc first: /** description */
  const jsdocMatch = content.match(/\/\*\*\s*\n?\s*\*?\s*([^\n*@][^\n]{0,120})/);
  if (jsdocMatch?.[1]) {
    return jsdocMatch[1].trim().replace(/\*\/$/, "").trim().slice(0, 80);
  }

  // Single-line // comment on the first non-blank, non-shebang line
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("//")) {
      const text = trimmed.replace(/^\/\/\s*/, "").trim();
      if (text.length > 3) return text.slice(0, 80);
    }
    // Python/Ruby # comment
    if ((ext === ".py" || ext === ".rb") && trimmed.startsWith("#") && !trimmed.startsWith("#!")) {
      const text = trimmed.replace(/^#\s*/, "").trim();
      if (text.length > 3) return text.slice(0, 80);
    }
    // Stop at first non-blank, non-comment line
    if (trimmed && !trimmed.startsWith("//") && !trimmed.startsWith("/*") && !trimmed.startsWith("*")) {
      break;
    }
  }

  return null;
}
